//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonProject.FolderData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salons
    {
        public int IdSalons { get; set; }
        public string NameSalons { get; set; }
        public decimal Cost { get; set; }
        public int IdServices { get; set; }
    
        public virtual Services Services { get; set; }
    }
}
